import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
import { assert, expect } from "chai";
import { network, deployments, ethers } from "hardhat";
import { developmentChains } from "../../helper-hardhat-config";
import { getNamedAccounts } from "hardhat";
import { Contract, Signer, BigNumber } from "ethers";
import { networkConfig } from "../../helper-hardhat-config";
import { Lottery } from "../../typechain-types/contracts/Lottery";
import { VRFCoordinatorV2Mock } from "../../typechain-types/@chainlink/contracts/src/v0.8/mocks";
import { Provider } from "@ethersproject/abstract-provider";
